name: Main CI

on: [push, pull_request]

jobs:
  changes:
    name: File changes filter
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Filter paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  client:
    name: Client CI
    needs: changes
    if: needs.changes.outputs.client == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit
      - name: Lint
        run: npm run lint

  server:
    name: Server CI
    needs: changes
    if: needs.changes.outputs.server == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: server/package-lock.json
      - run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit
      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Build
        run: npm run build

  docker-build-check:
    name: Server docker build check
    needs: changes
    if: >-
      needs.changes.outputs.server == 'true' && 
      (github.ref == 'refs/heads/main' || github.base_ref == 'main')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker build
        run: |
          docker build --target prod .
          docker build --target migrate .
  
  server-e2e:
    name: Server End to End Tests
    needs: changes
    if: >-
      needs.changes.outputs.server == 'true' && 
      (github.ref == 'refs/heads/main' || github.base_ref == 'main')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    services:
      db:
        image: postgres:18
        env:
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: app_password
          POSTGRES_DB: blog_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app_user -d blog_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: server/package-lock.json
      - run: npm ci
      
      - name: Migrate
        run: npx prisma migrate deploy --config ./prisma7.config.ts
        env:
          DATABASE_URL: postgresql://app_user:app_password@localhost:5432/blog_db
      - run: npx prisma generate

      - name: End to End Tests
        run: npm run test:e2e
        env:
          DATABASE_URL: postgresql://app_user:app_password@localhost:5432/blog_db


